#%RAML 1.0
title: Cursos Libres
version: v1
baseUri: api/v1/
protocols: HTTPS
mediaType: application/json

types:
## Listar profesor [comodin] ##
  ProfesorListadoResponseDTO:
    type: object
    properties:
      nombre: string
      especialidad: string
      anosExperiencia: integer
## Registro Cursos ##
  CursoRegistroRequestDTO:
    type: object
    properties:
      descripcion: string
      costo: number
      fechaInicio: date-only
      fechaFin: date-only
      turno:
        enum: [1, 2, 3]
        type: integer
        description: |
          1: mañana
          2: tarde
          3: noche
      lugar: string
      profesor: ProfesorListadoResponseDTO
  CursoRegistroResponseDTO:
    type: object
    properties:
      id: integer
      codigoRespuesta: string
      mensajeRespuesta: string
## Actualización Cursos ##
  CursoActualizacionRequestDTO:
    type: object
    properties:
      id: integer
      descripcion: string
      costo: number
      fechaInicio: date-only
      fechaFin: date-only
      turno:
        enum: [1, 2, 3]
        type: integer
        description: |
          1: mañana
          2: tarde
          3: noche
      lugar: string
      profesor: ProfesorListadoResponseDTO
  CursoActualizacionResponseDTO:
    type: object
    properties:
      codigoRespuesta: string
      mensajeRespuesta: string
## Listar todos los cursos de un alumno ##
  CursoListarPorAlumnoResponseDTO:
    type: object
    properties:
      id: integer
      descripcion: string
      turno: string
      lugar: string
      profesor: ProfesorListadoResponseDTO
  CursoListadoPorAlumnoResponseDTO:
    type: object
    properties:
      codigoRespuesta: string
      mensajeRespuesta: string
      cursos: CursoListarPorAlumnoResponseDTO[]
## Listar todos los cursos ##
  CursoListarResponseDTO:
    type: object
    properties:
      id: integer
      descripcion: string
      costo: number
      fechaInicio: date-only
      fechaFin: date-only
      turno: string
      lugar: string
      profesor: ProfesorListadoResponseDTO
  CursoListadoResponseDTO:
    type: object
    properties:
      codigoRespuesta: string
      mensajeRespuesta: string
      cursos: CursoListarResponseDTO[]

## Registro Alumnos ##
  AlumnoRegistroRequestDTO:
    type: object
    properties:
      nombres: string
      apellidos: string
      edad: integer
      telefono: string
      dni: string
      correo: string
      direccion: string
  AlumnoRegistroResponseDTO:
    type: object
    properties:
      id: integer
      codigoAlumno: string
      contrasena: string
      codigoRespuesta: string
      mensajeRespuesta: string
## Actualización Alumnos ##
  AlumnoActualizacionRequestDTO:
    type: object
    properties:
      id: integer
      contrasena: string
  AlumnoActualizacionResponseDTO:
    type: object
    properties:
      codigoRespuesta: string
      mensajeRespuesta: string
## Listar todos los alumnos de un curso ##
  AlumnoListarPorCursoResponseDTO:
    type: object
    properties:
      id: integer
      codigoAlumno: string
      nombres: string
      apellidos: string
  AlumnoListadoPorCursoResponseDTO:
    type: object
    properties:
      alumnos: AlumnoListarPorCursoResponseDTO[]
## Listar todos los alumnos ##
  AlumnoListarResponseDTO:
    type: object
    properties:
      id: integer
      codigoAlumno: string
      nombres: string
      apellidos: string
      edad: integer
      telefono: string
      dni: string
      correo: string
      direccion: string
  AlumnoListadoResponseDTO:
    type: object
    properties:
      codigoRespuesta: string
      mensajeRespuesta: string
      alumnos: AlumnoListarResponseDTO[]

## Matricular alumno a un curso ##
  InscripcionRegistroRequestDTO:
    type: object
    properties:
      idCurso: integer
      idAlumno: integer
  InscripcionRegistroResponseDTO:
    type: object
    properties:
      fechaInscripcion: date-only
      estado: string
      codigoRespuesta: string
      mensajeRespuesta: string
## Retirando alumno de un curso ##
  InscripcionRetiroRequestDTO:
    type: object
    properties:
      idAlumno: integer
      idCurso: integer
      estado:
        enum: [1, 2]
        type: integer
        description: |
          1: inscrito
          2: retirado
  InscripcionRetiroResponseDTO:
    type: object
    properties:
      codigoRespuesta: string
      mensajeRespuesta: string

/cursos:
  description: Recurso para administrar los cursos libres de CCLP
  post:
    description: Se registra un nuevo curso libre
    body:
      application/json:
        type: CursoRegistroRequestDTO
        example: |
          {
            "descripcion": "Serruchando el Piso",
            "costo": 420,
            "fechaInicio": "2020-01-15",
            "fechaFin": "2020-05-15",
            "turno": 2,
            "lugar": "La casa de cachi",
            "profesor":
              {
                "nombre": "El gran Bratzon",
                "especialidad": "Serruchar",
                "anosExperiencia": 4
              }
          }
    responses:
      201:
        body:
          application/json:
            type: CursoRegistroResponseDTO
            example: |
              {
                "id": 1,
                "codigoRespuesta": "01",
                "mensajeRespuesta": "Okis"
              }
  put:
    description: |
      Se actualiza un curso existente en base a su ID
    body:
      application/json:
        type: CursoActualizacionRequestDTO
        example: |
          {
            "id": 1,
            "descripcion": "Serruchando a Cachi",
            "costo": 300,
            "fechaInicio": "2019-11-30",
            "fechaFin": "2020-01-30",
            "turno": 3,
            "lugar": "La casa de cachi",
            "profesor":
              {
                "nombre": "El gran Bratzon",
                "especialidad": "Serruchar",
                "anosExperiencia": 4
              }
          }
    responses:
      200:
        body:
          application/json:
            type: CursoActualizacionResponseDTO
            example: |
              {
                "codigoRespuesta": "01",
                "mensajeRespuesta": "Okis"
              }
  /{codigo-alumno}:
    get:
      description: |
        Obtiene todos los cursos en los que un alumno está matriculado
      responses:
        200:
          body:
            application/json:
              type: CursoListadoPorAlumnoResponseDTO
              example: |
                {
                  "codigoRespuesta": "01",
                  "mensajeRespuesta": "Okis",
                  "cursos":
                    [
                      {
                        "id": 1,
                        "descripcion": "Serruchando el Piso",
                        "turno": "Tarde",
                        "lugar": "La casa de cachi",
                        "profesor":
                          {
                            "nombre": "El gran Bratzon",
                            "especialidad": "Serruchar",
                            "anosExperiencia": 4
                          }
                      },
                      {
                        "id": 2,
                        "descripcion": "El Kamasutra",
                        "turno": "Noche",
                        "lugar": "La casa de cachi",
                        "profesor":
                          {
                            "nombre": "El gran Bratzon",
                            "especialidad": "Serruchar",
                            "anosExperiencia": 4
                          }
                      }
                    ]
                }
  get:
    description: Obtiene todos los cursos libres de CCLP
    responses:
      200:
        body:
          application/json:
            type: CursoListadoResponseDTO
            example: |
              {
              "codigoRespuesta": "01",
              "mensajeRespuesta": "Okis",
              "cursos":
                [
                  {
                    "id": 1,
                    "descripcion": "Serruchando el Piso",
                    "costo": 420,
                    "fechaInicio": "2020-01-15",
                    "fechaFin": "2020-05-15",
                    "turno": "Tarde",
                    "lugar": "La casa de cachi",
                    "profesor":
                      {
                        "nombre": "El gran Bratzon",
                        "especialidad": "Serruchar",
                        "anosExperiencia": 4
                      }
                  },
                  {
                    "id": 2,
                    "descripcion": "El Kamasutra",
                    "costo": 620,
                    "fechaInicio": "2019-12-01",
                    "fechaFin": "2019-12-15",
                    "turno": "Noche",
                    "lugar": "La casa de cachi",
                    "profesor":
                      {
                        "nombre": "El gran Bratzon",
                        "especialidad": "Serruchar",
                        "anosExperiencia": 4
                      }
                  },
                  {
                    "id": 3,
                    "descripcion": "El Salto del Tigre",
                    "costo": 220,
                    "fechaInicio": "2019-12-10",
                    "fechaFin": "2019-12-17",
                    "turno": "Noche",
                    "lugar": "La casa de cachi",
                    "profesor":
                      {
                        "nombre": "El gran Bratzon",
                        "especialidad": "Serruchar",
                        "anosExperiencia": 4
                      }
                  }
                ]
              }
/alumnos:
  description: Recurso para administrar los alumnos de CCLP
  post:
    description: Se registra un nuevo alumno para CCLP
    body:
      application/json:
        type: AlumnoRegistroRequestDTO
        example: |
          {
            "nombres": "Juan Carlos",
            "apellidos": "Castillo Aycachi",
            "edad": 26,
            "telefono": "979666355",
            "dni": "70555913",
            "correo": "carlosjordi@hotmail.com",
            "direccion": "Las Margaritas Mz XXX Lt 69"
          }
    responses:
      201:
        body:
          application/json:
            type: AlumnoRegistroResponseDTO
            example: |
              {
                "id": 1,
                "codigoAlumno": "C19C0001",
                "contrasena": "C70555913A",
                "codigoRespuesta": "01",
                "mensajeRespuesta": "Okis"
              }
  put:
    description: Se actualiza la contrasena de un alumno
    body:
      application/json:
        type: AlumnoActualizacionRequestDTO
        example: |
          {
            "id": 1,
            "contrasena": "CachiWnReacciona"
          }
    responses:
      200:
        body:
          application/json:
            type: AlumnoActualizacionResponseDTO
            example: |
              {
                "codigoRespuesta": "01",
                "mensajeRespuesta": "Okis"
              }
  /{codigo-curso}:
    get:
      description: |
        Obtiene todos los alumnos matriculados en un mismo curso
      responses:
        200:
          body:
            application/json:
              type: AlumnoListadoPorCursoResponseDTO
              example: |
                {
                  "alumnos":
                    [
                      {
                        "id": 1,
                        "codigoAlumno": "C19C0001",
                        "nombres": "Juan Carlos",
                        "apellidos": "Castillo Aycachi"
                      },
                      {
                        "id": 2,
                        "codigoAlumno": "C19C0002",
                        "nombres": "Max Anthony",
                        "apellidos": "Cachi Ayala"
                      },
                      {
                        "id": 3,
                        "codigoAlumno": "C19L0003",
                        "nombres": "Gustavo Adolfo",
                        "apellidos": "Lizarzaburu Mercado"
                      },
                      {
                        "id": 4,
                        "codigoAlumno": "C19P0004",
                        "nombres": "El Bratzon Hilser",
                        "apellidos": "Serrucho Bada"
                      }
                    ]
                }
  get:
    responses:
      200:
        body:
          application/json:
            type: AlumnoListadoResponseDTO
            example: |
              {
                "codigoRespuesta": "01",
                "mensajeRespuesta": "Okis",
                "alumnos":
                  [
                    {
                      "id": 1,
                      "codigoAlumno": "C19C0001",
                      "nombres": "Juan Carlos",
                      "apellidos": "Castillo Aycachi",
                      "edad": 26,
                      "telefono": "979666355",
                      "dni": "70555913",
                      "correo": "carlosjordi@hotmail.com",
                      "direccion": "Las Margaritas Mz XXX Lt 69"
                    },
                    {
                      "id": 2,
                      "codigoAlumno": "C19C0002",
                      "nombres": "Max Anthony",
                      "apellidos": "Cachi Ayala",
                      "edad": 20,
                      "telefono": "999888777",
                      "dni": "70707070",
                      "correo": "anthonyca18m@gmail.com",
                      "direccion": "Comas City altura de San Pincho"
                    },
                    {
                      "id": 3,
                      "codigoAlumno": "C19L0003",
                      "nombres": "Gustavo Adolfo",
                      "apellidos": "Lizarzaburu Mercado",
                      "edad": 23,
                      "telefono": "929193965",
                      "dni": "96855263",
                      "correo": "glizarzaburu@gmail.com",
                      "direccion": "Al costado de melani"
                    },
                    {
                      "id": 4,
                      "codigoAlumno": "C19P0004",
                      "nombres": "El Bratzon Hilser",
                      "apellidos": "Serrucho Bada",
                      "edad": 99,
                      "telefono": "915152367",
                      "dni": "69696969",
                      "correo": "serruchador@profesional.pe",
                      "direccion": "La casa de melani"
                    },
                    {
                      "id": 5,
                      "codigoAlumno": "C19C0005",
                      "nombres": "Guti",
                      "apellidos": "Carreta",
                      "edad": 69,
                      "telefono": "926357482",
                      "dni": "88888888",
                      "correo": "elgutiton@de.guti.pe",
                      "direccion": "Los hoyos Nro.69"
                    }
                  ]
              }
/inscripciones:
  description: Recurso para administrar las inscripciones a CCLP
  post:
    description: |
      Inscribiendo un alumno a algún curso de CCLP
    body:
      application/json:
        type: InscripcionRegistroRequestDTO
        example: |
          {
            "idAlumno": 1,
            "idCurso": 1
          }
    responses:
      201:
        body:
          application/json:
            type: InscripcionRegistroResponseDTO
            example: |
              {
                "fechaInscripcion": "2019-11-22",
                "estado": "inscrito",
                "codigoRespuesta": "01",
                "mensajeRespuesta": "Okis"
              }
  put:
    description: |
      Retirando a un alumno de un curso CCLP
    body:
      application/json:
        type: InscripcionRetiroRequestDTO
        example: |
          {
            "idCurso": 1,
            "idAlumno": 1,
            "estado": 2
          }
    responses:
      200:
        body:
          application/json:
            type: InscripcionRetiroResponseDTO
            example: |
              {
                "codigoRespuesta": "01",
                "mensajeRespuesta": "Okis"
              }
