package pe.edu.idat.rest.persistence.domain;
// Generated 20/12/2019 11:30:41 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Alumno generated by hbm2java
 */
@Entity
@Table(name="alumno"
    ,catalog="cursoslibres"
)
public class Alumno  implements java.io.Serializable {


     private Long idAlumno;
     private String codigoAlumno;
     private String passAlumno;
     private String nombres;
     private String apellidos;
     private int edad;
     private String telefono;
     private String dni;
     private String correo;
     private String direccion;
     private Date fechaRegistro;
     private Set<Inscripcion> inscripcions = new HashSet<Inscripcion>(0);

    public Alumno() {
    }

	
    public Alumno(String codigoAlumno, String passAlumno, String nombres, String apellidos, int edad, String telefono, String dni, String correo, Date fechaRegistro) {
        this.codigoAlumno = codigoAlumno;
        this.passAlumno = passAlumno;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.edad = edad;
        this.telefono = telefono;
        this.dni = dni;
        this.correo = correo;
        this.fechaRegistro = fechaRegistro;
    }
    public Alumno(String codigoAlumno, String passAlumno, String nombres, String apellidos, int edad, String telefono, String dni, String correo, String direccion, Date fechaRegistro, Set<Inscripcion> inscripcions) {
       this.codigoAlumno = codigoAlumno;
       this.passAlumno = passAlumno;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.edad = edad;
       this.telefono = telefono;
       this.dni = dni;
       this.correo = correo;
       this.direccion = direccion;
       this.fechaRegistro = fechaRegistro;
       this.inscripcions = inscripcions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idAlumno", unique=true, nullable=false)
    public Long getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(Long idAlumno) {
        this.idAlumno = idAlumno;
    }

    
    @Column(name="codigoAlumno", nullable=false, length=10)
    public String getCodigoAlumno() {
        return this.codigoAlumno;
    }
    
    public void setCodigoAlumno(String codigoAlumno) {
        this.codigoAlumno = codigoAlumno;
    }

    
    @Column(name="passAlumno", nullable=false)
    public String getPassAlumno() {
        return this.passAlumno;
    }
    
    public void setPassAlumno(String passAlumno) {
        this.passAlumno = passAlumno;
    }

    
    @Column(name="nombres", nullable=false)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="apellidos", nullable=false)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="edad", nullable=false)
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }

    
    @Column(name="telefono", nullable=false, length=20)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="dni", nullable=false, length=20)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

    
    @Column(name="correo", nullable=false)
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }

    
    @Column(name="direccion")
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaRegistro", nullable=false, length=19)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="alumno")
    public Set<Inscripcion> getInscripcions() {
        return this.inscripcions;
    }
    
    public void setInscripcions(Set<Inscripcion> inscripcions) {
        this.inscripcions = inscripcions;
    }




}


