package pe.edu.idat.rest.persistence.domain;
// Generated 20/12/2019 11:30:41 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name="curso"
    ,catalog="cursoslibres"
)
public class Curso  implements java.io.Serializable {


     private Integer idCurso;
     private Profesor profesor;
     private String descripcion;
     private BigDecimal costo;
     private int vacantes;
     private int vacantesActuales;
     private Date fechaInicio;
     private Date fechaFin;
     private int turno;
     private String lugar;
     private Date fechaRegistro;
     private Set<Inscripcion> inscripcions = new HashSet<Inscripcion>(0);

    public Curso() {
    }

	
    public Curso(String descripcion, BigDecimal costo, int vacantes, int vacantesActuales, Date fechaInicio, Date fechaFin, int turno, String lugar, Date fechaRegistro) {
        this.descripcion = descripcion;
        this.costo = costo;
        this.vacantes = vacantes;
        this.vacantesActuales = vacantesActuales;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.turno = turno;
        this.lugar = lugar;
        this.fechaRegistro = fechaRegistro;
    }
    public Curso(Profesor profesor, String descripcion, BigDecimal costo, int vacantes, int vacantesActuales, Date fechaInicio, Date fechaFin, int turno, String lugar, Date fechaRegistro, Set<Inscripcion> inscripcions) {
       this.profesor = profesor;
       this.descripcion = descripcion;
       this.costo = costo;
       this.vacantes = vacantes;
       this.vacantesActuales = vacantesActuales;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.turno = turno;
       this.lugar = lugar;
       this.fechaRegistro = fechaRegistro;
       this.inscripcions = inscripcions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCurso", unique=true, nullable=false)
    public Integer getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(Integer idCurso) {
        this.idCurso = idCurso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idProfesor")
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }

    
    @Column(name="descripcion", nullable=false)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="costo", nullable=false, precision=7)
    public BigDecimal getCosto() {
        return this.costo;
    }
    
    public void setCosto(BigDecimal costo) {
        this.costo = costo;
    }

    
    @Column(name="vacantes", nullable=false)
    public int getVacantes() {
        return this.vacantes;
    }
    
    public void setVacantes(int vacantes) {
        this.vacantes = vacantes;
    }

    
    @Column(name="vacantesActuales", nullable=false)
    public int getVacantesActuales() {
        return this.vacantesActuales;
    }
    
    public void setVacantesActuales(int vacantesActuales) {
        this.vacantesActuales = vacantesActuales;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaInicio", nullable=false, length=10)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaFin", nullable=false, length=10)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    
    @Column(name="turno", nullable=false)
    public int getTurno() {
        return this.turno;
    }
    
    public void setTurno(int turno) {
        this.turno = turno;
    }

    
    @Column(name="lugar", nullable=false)
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaRegistro", nullable=false, length=19)
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="curso")
    public Set<Inscripcion> getInscripcions() {
        return this.inscripcions;
    }
    
    public void setInscripcions(Set<Inscripcion> inscripcions) {
        this.inscripcions = inscripcions;
    }




}


