package pe.edu.idat.rest.persistence.domain;
// Generated 20/12/2019 11:30:41 AM by Hibernate Tools 4.3.2-SNAPSHOT


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Inscripcion generated by hbm2java
 */
@Entity
@Table(name="inscripcion"
    ,catalog="cursoslibres"
)
public class Inscripcion  implements java.io.Serializable {


     private Integer idInscripcion;
     private Alumno alumno;
     private Curso curso;
     private int estado;
     private Date fechaInscripcion;

    public Inscripcion() {
    }

    public Inscripcion(Alumno alumno, Curso curso, int estado, Date fechaInscripcion) {
       this.alumno = alumno;
       this.curso = curso;
       this.estado = estado;
       this.fechaInscripcion = fechaInscripcion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idInscripcion", unique=true, nullable=false)
    public Integer getIdInscripcion() {
        return this.idInscripcion;
    }
    
    public void setIdInscripcion(Integer idInscripcion) {
        this.idInscripcion = idInscripcion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idAlumno", nullable=false)
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCurso", nullable=false)
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    
    @Column(name="estado", nullable=false)
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaInscripcion", nullable=false, length=19)
    public Date getFechaInscripcion() {
        return this.fechaInscripcion;
    }
    
    public void setFechaInscripcion(Date fechaInscripcion) {
        this.fechaInscripcion = fechaInscripcion;
    }




}


